# Generated by Django 5.0.6 on 2024-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('videoFile', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
