# Generated by Django 5.0.6 on 2024-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('1', 'COMEDY'), ('2', 'ACTION'), ('3', 'ROMANTIC'), ('4', 'HORROR'), ('5', 'SCIENCE FICTION')], default=1, max_length=20),
        ),
    ]
