# Generated by Django 5.0.6 on 2024-07-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('1', 'COMEDY'), ('2', 'ACTION'), ('3', 'ROMANTIC'), ('4', 'HORROR'), ('5', 'SCIENCE FICTION')], default=1, max_length=20, verbose_name='category'),
        ),
    ]
