# Generated by Django 5.0.6 on 2024-07-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0003_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
