# Generated by Django 5.0.6 on 2024-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0004_video_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planname', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('validity', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
