# Generated by Django 5.0.6 on 2024-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0005_subscription_plan_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan',
            name='validity',
            field=models.PositiveIntegerField(),
        ),
    ]
