# Generated by Django 5.0.6 on 2024-07-14 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0006_alter_subscription_plan_validity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_plan',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='id',
            new_name='_id',
        ),
        migrations.AddField(
            model_name='subscription_plan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
