# Generated by Django 5.0.6 on 2024-07-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0007_rename_id_subscription_plan__id_rename_id_video__id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_plan',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='_id',
            new_name='id',
        ),
    ]
