# Generated by Django 5.0.6 on 2024-07-16 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0008_rename__id_subscription_plan_id_rename__id_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='planAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
