# Generated by Django 5.0.6 on 2024-07-16 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0009_subscription_plan_planadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan',
            name='planAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
